# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build miryoku corne 42 qwerty vi'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_BT_CTLR_PHY_2M=n"]'
